### ISSUE TITLE
can you make animation opposite to current animation?

### ISSUE THREAD

**Issue by ghimireprashant** [matbeich/StickyCollectionView#2]
i try everything but was not able to opposite the effect.
thank buddy for your effort.

**Comment by matbeich** [comment]
Sorry, I don't understand what effect do you expect. Can you tell me a little bit more? :)

**Comment by ghimireprashant** [comment]
https://www.youtube.com/watch?v=-lvrU34Jt50 please check this animation as show in video.i want to make same animation.
